# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plover_cat\shortcut_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shortcutDialog(object):
    def setupUi(self, shortcutDialog):
        shortcutDialog.setObjectName("shortcutDialog")
        shortcutDialog.resize(391, 129)
        self.verticalLayout = QtWidgets.QVBoxLayout(shortcutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(shortcutDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.text_name = QtWidgets.QComboBox(shortcutDialog)
        self.text_name.setObjectName("text_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_name)
        self.label_2 = QtWidgets.QLabel(shortcutDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.shortcut = QtWidgets.QKeySequenceEdit(shortcutDialog)
        self.shortcut.setObjectName("shortcut")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shortcut)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.validate = QtWidgets.QPushButton(shortcutDialog)
        self.validate.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.validate.setObjectName("validate")
        self.horizontalLayout.addWidget(self.validate)
        self.buttonBox = QtWidgets.QDialogButtonBox(shortcutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(shortcutDialog)
        self.buttonBox.accepted.connect(shortcutDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(shortcutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(shortcutDialog)

    def retranslateUi(self, shortcutDialog):
        _translate = QtCore.QCoreApplication.translate
        shortcutDialog.setWindowTitle(_translate("shortcutDialog", "Dialog"))
        self.label.setText(_translate("shortcutDialog", "Menu Item"))
        self.label_2.setText(_translate("shortcutDialog", "Shortcut"))
        self.validate.setText(_translate("shortcutDialog", "Validate and save"))
